### ISSUE TITLE
[Profile] When signing up with email, the email is used in the profile URL

### ISSUE THREAD

**Issue by jeremi** [Meeds-io/meeds#131]
This is not ideal for preventing people from being spammed. The user should have the choice to make his email address public or not. 

```
https://builders.meeds.io/portal/meeds/profile/XXXX@newlogic.com
```
Instead, it should be an obscure ID.

**Comment by srenault-meeds** [comment]
Hi, 

We will provide a new way to display the profile. Indeed:
- when accessing a profile, the URL should not disclose any information related to the profile (username i.e). So a technical ID will be displayed in the URL instead of username, email, or public eth address depending how the user has been registered
- when trying to mention or to invite someone, the username won't be displayed anymore. Only the display name will be displayed

Hope that answers your question.

**Comment by srenault-meeds** [comment]
Duplicated with https://github.com/Meeds-io/meeds/issues/303
