### ISSUE TITLE
[Profile] Add editor in about me app

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#1428]
**Is your feature request related to a problem? Please describe.**
We can't format the profile about me

**Describe the solution you'd like**
Given I access my profile
When I add / update the field "About me"
Then the composer field proposes me the editor I used to have when writing a message
**But without the hashtag option**

--

Given previous step
When I save the about me
Then the format added when writing it and when using the editor (bullets, bold, quote, emojis, etc.) is also visible in my profile so it is consistent

**Comment by boubaker** [comment]
@rdenarie this one is impacting for you, knowing that it cleans deprecated APIs to deeply fixing a cache issue in Identity Management. I let you review the PRs and study impact on your codes. Those PRs was merged on develop-meed only to benifit from the fix in CI/CD of builders but not merged on develop yet to give you the time to consider possible impacts on compilation failures. Th list of PRs to review once done are:
- https://github.com/Meeds-io/gatein-portal/pull/779
- https://github.com/Meeds-io/social/pull/3300
- https://github.com/Meeds-io/gamification/pull/1388
- https://github.com/Meeds-io/kudos/pull/447
- https://github.com/Meeds-io/perk-store/pull/311
- https://github.com/Meeds-io/wallet/pull/479
- https://github.com/Meeds-io/notes/pull/898

Those changes was added to **feature/mips** BTW in order to help you study impacts where there will be compilation errors or not in your specific addons.

**Comment by boubaker** [comment]
> Those changes was added to **feature/mips** BTW in order to help you study impacts where there will be compilation errors or not in your specific addons.

![image](https://github.com/Meeds-io/meeds/assets/594824/03bc1073-eaf5-442e-a2d4-1402ce1bc0de)

Seems not impacting on build, thus we will proceed on merge on develop branch.
