### ISSUE TITLE
Point counted two time on the Meeds Twitter 

### ISSUE THREAD

**Issue by kuvaMan** [Meeds-io/meeds#1528]
I noticed my point repeated on the Twitter Tasks, 
It was duplicates.... I want to inform the team to work on the automatic X application, for a better and transparent work . Thanks

**Comment by plamarque** [comment]
Thanks for reporting. Is there a specific tweet that you saw was counted twice?

**Comment by plamarque** [comment]
probably related: I noticed that when someone posts 2 tweets closely in time (a few minutes), the two are accounted even so it should be rejected because the Twitter action is configured to be on a daily recurrence.

IMO in such case, both contributions should be captured in the backend, but the second one should be automatically rejected.

**Comment by srenault-meeds** [comment]
Fixed:
Comment to official tweets are no more considered
Depending on recurrence decided for the action, the contribution is captured accordingly
