### ISSUE TITLE
[Contributions] People are wrongly identified as "Disabled"

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/meeds#2057]
**Steps to reproduce**

1. Go check out the detail of an action 
2. Click on 'Participoa
3. See error: users are all identified as 'disabled', AKA 'deactivated'

<img width="263" alt="image" src="https://github.com/Meeds-io/meeds/assets/58853195/b1968378-68e0-4ab1-a229-c8c4cc894964">

**Expected behavior**

Only people actually deactivated must be considered as is

**Comment by srenault-meeds** [comment]
@margondicco @rdenarie can you please check this if possible? 
It is related to space / members app UX enhancement MIP

Thanks

**Comment by rdenarie** [comment]
Hi. 
It is a missing commit of this issue : https://github.com/Meeds-io/meeds/issues/1782

@ahamdi by checking exo task, I see the the gamification PR was merged on develop-exo and not on develop : 
https://github.com/Meeds-io/gamification/pull/1582
Can you check, confirm, and backport  ?

Thanks

**Comment by ahamdi** [comment]
@rdenarie my bad, I confirm
I will propose the PR for develop

**Comment by ahamdi** [comment]
This will solve https://github.com/Meeds-io/meeds/issues/1782 too

**Comment by srenault-meeds** [comment]
Hello, I can see a glitch. Have you already catched it?
It looks like a load is done with everybody disabled and then it is updated.
Problem: this is confusing


https://github.com/Meeds-io/meeds/assets/58853195/f8c7d024-c0ab-47f9-a5b0-8c83eed2d323

@rdenarie @ahamdi

**Comment by rdenarie** [comment]
Hi,
In ExoUserAvatar component, the value of enabled is false until the identity is loaded. 

So during the load of the identity we see the disabled icon, and when identity is fully load, we read enable property value, we detect that the user is enabled, and the icon disappear. 

I think we should open an issue to have the opposite behaviour : 
- since identity is not load, display nothing, when identity is load, display the disabled icon if necessary.

Do you take the action @srenault-meeds  ?

**Comment by srenault-meeds** [comment]
Ok thanks for the confirmation. Yes, we will see what we can do (in another issue of course)
