### ISSUE TITLE
Stream -link preview doesn't work

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/meeds#2227]
**Steps to reproduce**

1. Go to a space stream
2. copy paste an url (like this : https://www.lemonde.fr/culture/article/2024/04/17/les-films-a-l-affiche-la-machine-a-ecrire-et-autres-sources-de-tracas-l-ile-l-homme-aux-mille-visages-civil-war_6228211_3246.html) in a short message
3. See error : 

![image](https://github.com/Meeds-io/meeds/assets/31288011/1b8b0af3-3d8a-495e-8e55-aaf8b04cd1b4)

**Comment by srenault-meeds** [comment]
Hi @margondicco 

In fact, that's normal, due to a change in browsers for better security for users, see attached error in console:
> Access to image at '[https://img.lemde.fr/2024/04/16/0/150/1620/1080/1440/960/60/0/bef985d_17132...](https://img.lemde.fr/2024/04/16/0/150/1620/1080/1440/960/60/0/bef985d_1713254848092-f36b1e8-721-l-ile-mldfilms-2.jpg)' from origin 'http://localhost:8080/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

[lemonde.fr](https://lemonde.fr/) is missing an http header to allow the browser access the resource.

I also have tested it with different links and it is actually the same problem
I also have tested with brave, firefox or chrome browser and same problem.
