### ISSUE TITLE
[Profile] [Contributions] User profile - Challenges: Add achievment badges portlet

### ISSUE THREAD

**Issue by hbenali** [Meeds-io/meeds#233]
**Is your feature request related to a problem? Please describe.**
An achievement is published through an activity that can be forgotten over time.
**Describe the solution you'd like**
To encourage people to complete challenges, we need to make their achievements visible to all users. I suggest adding an achievements badge portlet. A badge must be chosen when creating a challenge, i.e. a user can select a template of badges (shapes and colors). We can take inspiration from the Github user profile achievement badges.

**Comment by plamarque** [comment]
Yes, some challenges _may_ be associated to badges that would be recognition rewards (in addition to the points associated to earning the badge). But probably not all challenges. 
Also, since for now all challenges are declarative-only, I think badges should be earnt only after the challenge has been verified (either automatically or manually).

+1 for having a UI to display one's badges. It could be a block on the profile page. I think we could even let user pick which badges he wants to highlight or not as they are a way to build reputation in a community.

**Comment by srenault-meeds** [comment]
Will be considered in badges rework
