### ISSUE TITLE
[Profile] User meeds wallet as username for self registered users

### ISSUE THREAD

**Issue by plamarque** [Meeds-io/meeds#303]
**Is your feature request related to a problem? Please describe.**
Currently, where a user creatres an account manually by email, the username it automatically set to its email. It's not a desirable behaviour privacy-wide.  
In comparison, where using Metamask to create a user account, the public key of the Ethereum account is used as the username. This behaviour better preserves user privacy. At least it doesn't expose their email directly.

**Describe the solution you'd like**
When user creates a new account by email, I suggest to generate their meeds wallet in the process, and use the wallet's public key as the username. This would consistently create usernames and improve privacy.

**Describe alternatives you've considered**
Alternatively, username could be made fully random no matter the registration method, but we could set the public key as the display name by default, while letting user fully customize their display name. This way, they would have full control on what they expose. 

**Additional context**
* User with an email and password, should still be able to login with those as credentials.
* using public keys as immutable usernames on meeds is arguably problematic because users may want to change the eth account they connect to the deed at some point in the future.

**Comment by srenault-meeds** [comment]
Hi, 

We will provide a new way to display the profile. Indeed:
- when accessing a profile, the URL should not disclose any information related to the profile (username i.e). So a technical ID will be displayed in the URL instead of username, email, or public eth address depending how the user has been registered
- when trying to mention or to invite someone, the username won't be displayed anymore. Only the display name will be displayed

Hope that answers your question.

**Comment by srenault-meeds** [comment]
From now on, users that sign up have a username composed that way [firstname].[lastname]
