### ISSUE TITLE
[Contributions] Users order list by reward domain not displayed in people list page

### ISSUE THREAD

**Issue by SaraBoutej** [Meeds-io/meeds#319]
Steps to reproduce

Go to '"People list page"
Go to "Leadership portlet in the right sidebar"
Try to choose an option between the dropdown options (teamwork, social, rewards...)

Current behaviour

Nothing happen when trying to click on a new option

Expected behavior
By clicking on a new option in the dropdown, a list of users ordered by points earned in the option domain must displayed
![Screenshot from 2022-09-30 17-21-57](https://user-images.githubusercontent.com/40363501/193314332-27c92bad-ac9a-45a0-bfa9-1e6d6319d342.png)

**Comment by srenault-meeds** [comment]
Actually, the problem is that domain that are listed there are not enabled or have been removed. This is why you cannot see anything. The suggestion to fix this should be: when a program (aka domain) is disabled or removed, then this shouldn't be listed in this dropdown.
@Imenmakni can you please catch this?
Thanks

**Comment by srenault-meeds** [comment]
Fixed
