### ISSUE TITLE
 UI issue while using source mode full screen

### ISSUE THREAD

**Issue by GouadriaHanen** [Meeds-io/meeds#752]
steps
sidebar>administration>backoffice
new content> web content
type some text in the main content editor
source button> full screen

actual
bad display of the interface

screencast
https://youtu.be/29F8Wyqqilk

**Comment by boubaker** [comment]
@GouadriaHanen what is `web content` is it Meeds Feature ? Can you attach screenshot as well please to precise more the problem. Thanks.

**Comment by srenault-meeds** [comment]
Hello I confirm I don't understand why it is considered as meeds related.
cc @rdenarie WDYT?

**Comment by srenault-meeds** [comment]
Maybe because ckeditor is used there as it is used elsewhere in meeds?

**Comment by GouadriaHanen** [comment]
screencast
https://youtu.be/29F8Wyqqilk

**Comment by rdenarie** [comment]
The meeds issue is created because the fix is located in the commons css of Ckeditor, which is in meeds-io repository.

So, the process we define require the creation of a meeds issue.

BUT, @GouadriaHanen you have to "decontextualize" the issue, as meeds do not have backoffice, webcontent ...
You have to reword the issue to describe the problem with a "meeds" point of view.

For example : 
When using the "Source" ckeditor addon in full screen there is a problem which ....
This source button is not used directly in meeds context, but is present in meeds codebase.
...

Thank you

**Comment by srenault-meeds** [comment]
Is it done then?

**Comment by rdenarie** [comment]
Yes, it is, thanks
