### ISSUE TITLE
Allow to mark all spaces as read

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#804]
**Is your feature request related to a problem? Please describe.**
I have a lot of unread spaces, too much to take time to read them one by one :
![2023-03-14_09-50](https://user-images.githubusercontent.com/807839/224946887-48f624a5-ec0f-4f0b-a662-2706dd0bd4ed.png)

Now, with the new feature displaying the red dot in the hamburger menu, I litterally ALWAYS see the red dot. 
I wish to be able to mark all as read, as I can do with notifications.

**Comment by rdenarie** [comment]
To complete this issue : 
When you have new activities in a space you not visited since a while, you always to open the first left menu drawer, then the second to see all spaces, then click on show more to see more spaces. With lot of spaces, it is very painful to mark all spaces as read, one by one !

We need something to mark all activites as read OR a new filter in activity stream to display only unread activities. So we can browse it never mind the space in which the activities are.

**Comment by boubaker** [comment]
May be automatically mark notifications older than 7 days as read since it's not pertinent to keep the unread indicator on it. @srenault-meeds WDYT ?

**Comment by srenault-meeds** [comment]
Indeed that could be something interested to provide. 
I like the filter too because sometimes it is a space I don't browse from a long time. And to know which one it is, I need to look for in the recent spaces panel. 

So we might need both options.

**Comment by rdenarie** [comment]
For me, mark all as read after 7 days is too hard. 

Some users prefer take the time to read all one by one, even if notif are old, and some wish to mark all as read. 
Sometimes, this is the same user which can make both, at a different time.

We should let the choice on how to consume it easily (the filter), but provide option to manage it all in one action (read it all).

**Comment by boubaker** [comment]
In fact we already use the cleanup strategy on Web Notifications, each 30 days, see it here
https://github.com/Meeds-io/commons/blob/c70f0296ac6cdfd74062c70a2709ec34e27f7c85/commons-extension-webapp/src/main/webapp/WEB-INF/conf/commons-extension/notification-configuration.xml#L272
( Since the beginning, see it here [property name="liveDays](https://github.com/Meeds-io/commons/blob/02df0f8918caadae7e3e67594b63d280b40f464e/commons-extension-webapp/src/main/webapp/WEB-INF/conf/commons-extension/notification-configuration.xml#L268) )

IMO, to make this coherent with Web notifs, we should clean Space Unread Channel data each 30 days as well.

**Comment by srenault-meeds** [comment]
An option to filter the stream to only unread activities has been provided few days ago and this can be done from the general stream or in a space stream.
So I consider this one as enhanced and done.
